namespace XpandPwsh.Cmdlets.Gac{
    internal enum AssemblyNameProperty{
        PublicKey = 0,
        PublicKeyToken,
        HashValue,
        Name,
        MajorVersion,
        MinorVersion,
        BuildNumber,
        RevisionNumber,
        Culture,
        ProcessorIdArray,
        OSInfoArray,
        HashAlgId,
        Alias,
        CodebaseUrl,
        CodebaseLastMod,
        NullPublicKey,
        NullPublicKeyToken,
        Custom,
        NullCustom,
        Mvid,
        FileMajroVersion,
        FileMinorVersion,
        FileBuildNumber,
        FileRevisionNumber,
        Retarget,
        SignatureBlob,
        ConfigMask,
        Architecture,
        MaxParams
    }
}